services:
  into1:
    image: intento:into
    restart: always
    volumes:
      - ./state/into1:/home/intento/.intento
    ports:
      - "26657:26657"
      - "26656:26656"
      - "1317:1317"
      - "9090:9090"

  into2:
    image: intento:into
    volumes:
      - ./state/into2:/home/intento/.intento

  into3:
    image: intento:into
    volumes:
      - ./state/into3:/home/intento/.intento

  gaia1:
    restart: always
    image: intento:gaia
    volumes:
      - ./state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"

  gaia2:
    image: intento:gaia
    volumes:
      - ./state/gaia2:/home/gaia/.gaia

  gaia3:
    image: intento:gaia
    volumes:
      - ./state/gaia3:/home/gaia/.gaia

  gaia4:
    image: intento:gaia
    volumes:
      - ./state/gaia4:/home/gaia/.gaia

  gaia5:
    image: intento:gaia
    volumes:
      - ./state/gaia5:/home/gaia/.gaia

  osmo1:
    image: intento:osmo
    volumes:
      - ./state/osmo1:/home/osmosis/.osmosisd
    ports:
      - "26357:26657"
      - "1287:1317"
      - "9060:9090"

  osmo2:
    image: intento:osmo
    volumes:
      - ./state/osmo2:/home/osmosis/.osmosisd

  osmo3:
    image: intento:osmo
    volumes:
      - ./state/osmo3:/home/osmosis/.osmosisd

  osmo4:
    image: intento:osmo
    volumes:
      - ./state/osmo4:/home/osmosis/.osmosisd

  osmo5:
    image: intento:osmo
    volumes:
      - ./state/osmo5:/home/osmosis/.osmosisd

  # For the host chain, we must override the command to prevent an old binary from
  # being run when testing upgrades
  host1:
    image: intento:into
    command: intentod start
    volumes:
      - ./state/host1:/home/into/.intento
    ports:
      - "26157:26657"
      - "1267:1317"
      - "9040:9090"

  host2:
    image: intento:into
    command: intentod start
    volumes:
      - ./state/host2:/home/into/.intento

  host3:
    image: intento:into
    command: intentod start
    volumes:
      - ./state/host3:/home/into/.intento

  host4:
    image: intento:into
    command: intentod start
    volumes:
      - ./state/host4:/home/into/.intento

  host5:
    image: intento:into
    command: intentod start
    volumes:
      - ./state/host5:/home/into/.intento

  # Fill in new host zone being tested here

  hermes:
    image: intento:hermes
    volumes:
      - ./state/hermes:/home/hermes/.hermes
    restart: always

  relayer-gaia:
    image: intento:relayer
    volumes:
      - ./state/relayer-gaia:/home/relayer/.relayer
      
    restart: always
    command: [ "bash", "start.sh", "into-gaia" ]

  relayer-osmo:
    image: intento:relayer
    volumes:
      - ./state/relayer-osmo:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "into-osmo" ]

  relayer-host:
    image: intento:relayer
    volumes:
      - ./state/relayer-host:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "into-host" ]