// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tpp/buyer.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Buyer struct {
	Buyer        string     `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Itemid       string     `protobuf:"bytes,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Transferable bool       `protobuf:"varint,3,opt,name=transferable,proto3" json:"transferable,omitempty"`
	Deposit      types.Coin `protobuf:"bytes,4,opt,name=deposit,proto3" json:"deposit"`
}

func (m *Buyer) Reset()         { *m = Buyer{} }
func (m *Buyer) String() string { return proto.CompactTextString(m) }
func (*Buyer) ProtoMessage()    {}
func (*Buyer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4868296580ce0529, []int{0}
}
func (m *Buyer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Buyer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Buyer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Buyer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Buyer.Merge(m, src)
}
func (m *Buyer) XXX_Size() int {
	return m.Size()
}
func (m *Buyer) XXX_DiscardUnknown() {
	xxx_messageInfo_Buyer.DiscardUnknown(m)
}

var xxx_messageInfo_Buyer proto.InternalMessageInfo

func (m *Buyer) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *Buyer) GetItemid() string {
	if m != nil {
		return m.Itemid
	}
	return ""
}

func (m *Buyer) GetTransferable() bool {
	if m != nil {
		return m.Transferable
	}
	return false
}

func (m *Buyer) GetDeposit() types.Coin {
	if m != nil {
		return m.Deposit
	}
	return types.Coin{}
}

type MsgCreateBuyer struct {
	Buyer   string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Itemid  string `protobuf:"bytes,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Deposit int64  `protobuf:"varint,3,opt,name=deposit,proto3" json:"deposit,omitempty"`
}

func (m *MsgCreateBuyer) Reset()         { *m = MsgCreateBuyer{} }
func (m *MsgCreateBuyer) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBuyer) ProtoMessage()    {}
func (*MsgCreateBuyer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4868296580ce0529, []int{1}
}
func (m *MsgCreateBuyer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBuyer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBuyer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBuyer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBuyer.Merge(m, src)
}
func (m *MsgCreateBuyer) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBuyer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBuyer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBuyer proto.InternalMessageInfo

func (m *MsgCreateBuyer) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgCreateBuyer) GetItemid() string {
	if m != nil {
		return m.Itemid
	}
	return ""
}

func (m *MsgCreateBuyer) GetDeposit() int64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

type MsgUpdateBuyer struct {
	Buyer        string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Itemid       string `protobuf:"bytes,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Transferable bool   `protobuf:"varint,3,opt,name=transferable,proto3" json:"transferable,omitempty"`
	Deposit      int64  `protobuf:"varint,4,opt,name=deposit,proto3" json:"deposit,omitempty"`
}

func (m *MsgUpdateBuyer) Reset()         { *m = MsgUpdateBuyer{} }
func (m *MsgUpdateBuyer) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBuyer) ProtoMessage()    {}
func (*MsgUpdateBuyer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4868296580ce0529, []int{2}
}
func (m *MsgUpdateBuyer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBuyer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBuyer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBuyer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBuyer.Merge(m, src)
}
func (m *MsgUpdateBuyer) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBuyer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBuyer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBuyer proto.InternalMessageInfo

func (m *MsgUpdateBuyer) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgUpdateBuyer) GetItemid() string {
	if m != nil {
		return m.Itemid
	}
	return ""
}

func (m *MsgUpdateBuyer) GetTransferable() bool {
	if m != nil {
		return m.Transferable
	}
	return false
}

func (m *MsgUpdateBuyer) GetDeposit() int64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

type MsgDeleteBuyer struct {
	Buyer  string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Itemid string `protobuf:"bytes,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
}

func (m *MsgDeleteBuyer) Reset()         { *m = MsgDeleteBuyer{} }
func (m *MsgDeleteBuyer) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteBuyer) ProtoMessage()    {}
func (*MsgDeleteBuyer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4868296580ce0529, []int{3}
}
func (m *MsgDeleteBuyer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteBuyer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteBuyer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteBuyer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteBuyer.Merge(m, src)
}
func (m *MsgDeleteBuyer) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteBuyer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteBuyer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteBuyer proto.InternalMessageInfo

func (m *MsgDeleteBuyer) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgDeleteBuyer) GetItemid() string {
	if m != nil {
		return m.Itemid
	}
	return ""
}

type MsgItemTransfer struct {
	Buyer        string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Itemid       string `protobuf:"bytes,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Transferable bool   `protobuf:"varint,3,opt,name=transferable,proto3" json:"transferable,omitempty"`
}

func (m *MsgItemTransfer) Reset()         { *m = MsgItemTransfer{} }
func (m *MsgItemTransfer) String() string { return proto.CompactTextString(m) }
func (*MsgItemTransfer) ProtoMessage()    {}
func (*MsgItemTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_4868296580ce0529, []int{4}
}
func (m *MsgItemTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgItemTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgItemTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgItemTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgItemTransfer.Merge(m, src)
}
func (m *MsgItemTransfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgItemTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgItemTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgItemTransfer proto.InternalMessageInfo

func (m *MsgItemTransfer) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgItemTransfer) GetItemid() string {
	if m != nil {
		return m.Itemid
	}
	return ""
}

func (m *MsgItemTransfer) GetTransferable() bool {
	if m != nil {
		return m.Transferable
	}
	return false
}

type MsgItemThank struct {
	Buyer  string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Itemid string `protobuf:"bytes,2,opt,name=itemid,proto3" json:"itemid,omitempty"`
	Thank  bool   `protobuf:"varint,3,opt,name=thank,proto3" json:"thank,omitempty"`
}

func (m *MsgItemThank) Reset()         { *m = MsgItemThank{} }
func (m *MsgItemThank) String() string { return proto.CompactTextString(m) }
func (*MsgItemThank) ProtoMessage()    {}
func (*MsgItemThank) Descriptor() ([]byte, []int) {
	return fileDescriptor_4868296580ce0529, []int{5}
}
func (m *MsgItemThank) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgItemThank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgItemThank.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgItemThank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgItemThank.Merge(m, src)
}
func (m *MsgItemThank) XXX_Size() int {
	return m.Size()
}
func (m *MsgItemThank) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgItemThank.DiscardUnknown(m)
}

var xxx_messageInfo_MsgItemThank proto.InternalMessageInfo

func (m *MsgItemThank) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgItemThank) GetItemid() string {
	if m != nil {
		return m.Itemid
	}
	return ""
}

func (m *MsgItemThank) GetThank() bool {
	if m != nil {
		return m.Thank
	}
	return false
}

func init() {
	proto.RegisterType((*Buyer)(nil), "danieljdd.tpp.tpp.Buyer")
	proto.RegisterType((*MsgCreateBuyer)(nil), "danieljdd.tpp.tpp.MsgCreateBuyer")
	proto.RegisterType((*MsgUpdateBuyer)(nil), "danieljdd.tpp.tpp.MsgUpdateBuyer")
	proto.RegisterType((*MsgDeleteBuyer)(nil), "danieljdd.tpp.tpp.MsgDeleteBuyer")
	proto.RegisterType((*MsgItemTransfer)(nil), "danieljdd.tpp.tpp.MsgItemTransfer")
	proto.RegisterType((*MsgItemThank)(nil), "danieljdd.tpp.tpp.MsgItemThank")
}

func init() { proto.RegisterFile("tpp/buyer.proto", fileDescriptor_4868296580ce0529) }

var fileDescriptor_4868296580ce0529 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xbd, 0x4e, 0xeb, 0x30,
	0x14, 0xc7, 0xe3, 0xdb, 0x8f, 0x7b, 0xaf, 0x6f, 0x75, 0x2b, 0xa2, 0x0a, 0x85, 0x0e, 0xa1, 0x8a,
	0x18, 0x3a, 0xc5, 0x2a, 0x4c, 0x2c, 0x1d, 0x5a, 0x16, 0x86, 0x2e, 0x11, 0x48, 0x88, 0xcd, 0x49,
	0x0e, 0xa9, 0xa1, 0x89, 0xad, 0xd8, 0x45, 0x54, 0xe2, 0x21, 0x18, 0x78, 0xa8, 0x8e, 0x1d, 0x99,
	0x10, 0x6a, 0x5f, 0x04, 0xd9, 0x49, 0x29, 0xdd, 0xa0, 0x62, 0xb0, 0xe5, 0xf3, 0xe1, 0xff, 0xef,
	0x7f, 0xa4, 0x83, 0x9b, 0x4a, 0x08, 0x12, 0x4e, 0x67, 0x90, 0xfb, 0x22, 0xe7, 0x8a, 0xdb, 0x7b,
	0x31, 0xcd, 0x18, 0x4c, 0x6e, 0xe3, 0xd8, 0x57, 0x42, 0xe8, 0xd3, 0x6e, 0x25, 0x3c, 0xe1, 0xa6,
	0x4a, 0xf4, 0xab, 0x68, 0x6c, 0xbb, 0x11, 0x97, 0x29, 0x97, 0x24, 0xa4, 0x12, 0xc8, 0x7d, 0x2f,
	0x04, 0x45, 0x7b, 0x24, 0xe2, 0x2c, 0x2b, 0xea, 0xde, 0x33, 0xc2, 0xb5, 0x81, 0x16, 0xb6, 0x5b,
	0xb8, 0x66, 0x08, 0x0e, 0xea, 0xa0, 0xee, 0xdf, 0xa0, 0x08, 0xec, 0x7d, 0x5c, 0x67, 0x0a, 0x52,
	0x16, 0x3b, 0xbf, 0x4c, 0xba, 0x8c, 0x6c, 0x0f, 0x37, 0x54, 0x4e, 0x33, 0x79, 0x03, 0x39, 0x0d,
	0x27, 0xe0, 0x54, 0x3a, 0xa8, 0xfb, 0x27, 0xd8, 0xca, 0xd9, 0xa7, 0xf8, 0x77, 0x0c, 0x82, 0x4b,
	0xa6, 0x9c, 0x6a, 0x07, 0x75, 0xff, 0x1d, 0x1f, 0xf8, 0x85, 0x1b, 0x5f, 0xbb, 0xf1, 0x4b, 0x37,
	0xfe, 0x90, 0xb3, 0x6c, 0x50, 0x9d, 0xbf, 0x1e, 0x5a, 0xc1, 0xba, 0xdf, 0xbb, 0xc2, 0xff, 0x47,
	0x32, 0x19, 0xe6, 0x40, 0x15, 0xec, 0x62, 0xcf, 0xd9, 0xa0, 0xb5, 0xb3, 0xca, 0x46, 0xf9, 0xd1,
	0x28, 0x5f, 0x8a, 0x78, 0x47, 0xe5, 0xaf, 0x0c, 0xee, 0x6c, 0x0f, 0xfe, 0x89, 0xde, 0x37, 0xf4,
	0x33, 0x98, 0xc0, 0x4e, 0x74, 0x2f, 0xc2, 0xcd, 0x91, 0x4c, 0xce, 0x15, 0xa4, 0x17, 0x25, 0xf0,
	0xe7, 0xed, 0x7b, 0x01, 0x6e, 0xac, 0x21, 0x63, 0x9a, 0xdd, 0x7d, 0x93, 0xd0, 0xc2, 0x35, 0xa5,
	0xbf, 0x95, 0xd2, 0x45, 0x30, 0xe8, 0xcf, 0x97, 0x2e, 0x5a, 0x2c, 0x5d, 0xf4, 0xb6, 0x74, 0xd1,
	0xd3, 0xca, 0xb5, 0x16, 0x2b, 0xd7, 0x7a, 0x59, 0xb9, 0xd6, 0xf5, 0x51, 0xc2, 0xd4, 0x78, 0x1a,
	0xfa, 0x11, 0x4f, 0xc9, 0xc7, 0x56, 0x13, 0xbd, 0xf0, 0x0f, 0xe6, 0x56, 0x33, 0x01, 0x32, 0xac,
	0x9b, 0x75, 0x3d, 0x79, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xf6, 0x86, 0x25, 0x0a, 0x03, 0x00,
	0x00,
}

func (m *Buyer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Buyer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Buyer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Deposit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBuyer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Transferable {
		i--
		if m.Transferable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Itemid) > 0 {
		i -= len(m.Itemid)
		copy(dAtA[i:], m.Itemid)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Itemid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateBuyer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBuyer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBuyer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Deposit != 0 {
		i = encodeVarintBuyer(dAtA, i, uint64(m.Deposit))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Itemid) > 0 {
		i -= len(m.Itemid)
		copy(dAtA[i:], m.Itemid)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Itemid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBuyer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBuyer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBuyer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Deposit != 0 {
		i = encodeVarintBuyer(dAtA, i, uint64(m.Deposit))
		i--
		dAtA[i] = 0x20
	}
	if m.Transferable {
		i--
		if m.Transferable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Itemid) > 0 {
		i -= len(m.Itemid)
		copy(dAtA[i:], m.Itemid)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Itemid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteBuyer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteBuyer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteBuyer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Itemid) > 0 {
		i -= len(m.Itemid)
		copy(dAtA[i:], m.Itemid)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Itemid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgItemTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgItemTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgItemTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Transferable {
		i--
		if m.Transferable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Itemid) > 0 {
		i -= len(m.Itemid)
		copy(dAtA[i:], m.Itemid)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Itemid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgItemThank) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgItemThank) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgItemThank) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Thank {
		i--
		if m.Thank {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Itemid) > 0 {
		i -= len(m.Itemid)
		copy(dAtA[i:], m.Itemid)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Itemid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintBuyer(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBuyer(dAtA []byte, offset int, v uint64) int {
	offset -= sovBuyer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Buyer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	l = len(m.Itemid)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	if m.Transferable {
		n += 2
	}
	l = m.Deposit.Size()
	n += 1 + l + sovBuyer(uint64(l))
	return n
}

func (m *MsgCreateBuyer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	l = len(m.Itemid)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	if m.Deposit != 0 {
		n += 1 + sovBuyer(uint64(m.Deposit))
	}
	return n
}

func (m *MsgUpdateBuyer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	l = len(m.Itemid)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	if m.Transferable {
		n += 2
	}
	if m.Deposit != 0 {
		n += 1 + sovBuyer(uint64(m.Deposit))
	}
	return n
}

func (m *MsgDeleteBuyer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	l = len(m.Itemid)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	return n
}

func (m *MsgItemTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	l = len(m.Itemid)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	if m.Transferable {
		n += 2
	}
	return n
}

func (m *MsgItemThank) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	l = len(m.Itemid)
	if l > 0 {
		n += 1 + l + sovBuyer(uint64(l))
	}
	if m.Thank {
		n += 2
	}
	return n
}

func sovBuyer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBuyer(x uint64) (n int) {
	return sovBuyer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Buyer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuyer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Buyer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Buyer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Itemid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Itemid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transferable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Transferable = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBuyer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBuyer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBuyer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuyer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBuyer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBuyer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Itemid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Itemid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			m.Deposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deposit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBuyer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBuyer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBuyer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuyer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBuyer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBuyer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Itemid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Itemid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transferable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Transferable = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			m.Deposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deposit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBuyer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBuyer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteBuyer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuyer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteBuyer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteBuyer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Itemid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Itemid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBuyer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBuyer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgItemTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuyer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgItemTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgItemTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Itemid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Itemid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transferable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Transferable = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBuyer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBuyer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgItemThank) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBuyer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgItemThank: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgItemThank: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Itemid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBuyer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBuyer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Itemid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Thank", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Thank = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipBuyer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBuyer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBuyer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBuyer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBuyer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBuyer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBuyer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBuyer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBuyer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBuyer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBuyer = fmt.Errorf("proto: unexpected end of group")
)
