// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trst/autoibctx/v1beta1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	types2 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AutoTxInfo stores the info for the auto executing interchain accounts transaction
type AutoTxInfo struct {
	TxID          uint64                  `protobuf:"varint,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Owner         string                  `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Label         string                  `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	FeeAddress    string                  `protobuf:"bytes,4,opt,name=fee_address,json=feeAddress,proto3" json:"fee_address,omitempty"`
	Msgs          []*types.Any            `protobuf:"bytes,5,rep,name=msgs,proto3" json:"msgs,omitempty"`
	Interval      time.Duration           `protobuf:"bytes,6,opt,name=interval,proto3,stdduration" json:"interval,omitempty"`
	StartTime     time.Time               `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	ExecTime      time.Time               `protobuf:"bytes,8,opt,name=exec_time,json=execTime,proto3,stdtime" json:"exec_time"`
	EndTime       time.Time               `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time"`
	UpdateHistory []time.Time             `protobuf:"bytes,10,rep,name=update_history,json=updateHistory,proto3,stdtime" json:"update_history"`
	ICAConfig     *ICAConfig              `protobuf:"bytes,11,opt,name=ica_config,json=icaConfig,proto3" json:"ica_config,omitempty"`
	Configuration *ExecutionConfiguration `protobuf:"bytes,12,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (m *AutoTxInfo) Reset()         { *m = AutoTxInfo{} }
func (m *AutoTxInfo) String() string { return proto.CompactTextString(m) }
func (*AutoTxInfo) ProtoMessage()    {}
func (*AutoTxInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f87850278d17cf9d, []int{0}
}
func (m *AutoTxInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AutoTxInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AutoTxInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AutoTxInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoTxInfo.Merge(m, src)
}
func (m *AutoTxInfo) XXX_Size() int {
	return m.Size()
}
func (m *AutoTxInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoTxInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AutoTxInfo proto.InternalMessageInfo

type ICAConfig struct {
	PortID           string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ConnectionID     string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	HostConnectionID string `protobuf:"bytes,3,opt,name=host_connection_id,json=hostConnectionId,proto3" json:"host_connection_id,omitempty"`
}

func (m *ICAConfig) Reset()         { *m = ICAConfig{} }
func (m *ICAConfig) String() string { return proto.CompactTextString(m) }
func (*ICAConfig) ProtoMessage()    {}
func (*ICAConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f87850278d17cf9d, []int{1}
}
func (m *ICAConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ICAConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ICAConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ICAConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ICAConfig.Merge(m, src)
}
func (m *ICAConfig) XXX_Size() int {
	return m.Size()
}
func (m *ICAConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ICAConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ICAConfig proto.InternalMessageInfo

// ExecutionConfiguration provides the execution-related configuration of the AutoTx
type ExecutionConfiguration struct {
	// if true, the AutoTx outputs are saved and can be used in condition-based logic
	SaveMsgResponses bool `protobuf:"varint,1,opt,name=save_msg_responses,json=saveMsgResponses,proto3" json:"save_msg_responses,omitempty"`
	// if true, the AutoTx is not updatable
	UpdatingDisabled bool `protobuf:"varint,2,opt,name=updating_disabled,json=updatingDisabled,proto3" json:"updating_disabled,omitempty"`
	// If true, will execute until we get a successful AutoTx, if false/unset will always execute
	StopOnSuccess bool `protobuf:"varint,3,opt,name=stop_on_success,json=stopOnSuccess,proto3" json:"stop_on_success,omitempty"`
	// If true, will execute until successful AutoTx, if false/unset will always execute
	StopOnFailure bool `protobuf:"varint,4,opt,name=stop_on_failure,json=stopOnFailure,proto3" json:"stop_on_failure,omitempty"`
	// If true, owner account balance is used when trigger account funds run out
	FallbackToOwnerBalance bool `protobuf:"varint,5,opt,name=fallback_to_owner_balance,json=fallbackToOwnerBalance,proto3" json:"fallback_to_owner_balance,omitempty"`
	// If true, allows the AutoTx to continue execution after an ibc channel times out (recommended)
	ReregisterICAAfterTimeout bool `protobuf:"varint,6,opt,name=reregister_ica_after_timeout,json=reregisterIcaAfterTimeout,proto3" json:"reregister_ica_after_timeout,omitempty"`
}

func (m *ExecutionConfiguration) Reset()         { *m = ExecutionConfiguration{} }
func (m *ExecutionConfiguration) String() string { return proto.CompactTextString(m) }
func (*ExecutionConfiguration) ProtoMessage()    {}
func (*ExecutionConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_f87850278d17cf9d, []int{2}
}
func (m *ExecutionConfiguration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionConfiguration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecutionConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionConfiguration.Merge(m, src)
}
func (m *ExecutionConfiguration) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionConfiguration proto.InternalMessageInfo

// ExecutionConditions provides execution conditions for the AutoTx
type ExecutionConditions struct {
	//optional array of dependent AutoTxs that when executing succesfully, stops further execution
	StopOnSuccessOf []int64 `protobuf:"varint,5,rep,packed,name=stop_on_success_of,json=stopOnSuccessOf,proto3" json:"stop_on_success_of,omitempty"`
	//optional array of dependent AutoTxs that when not executing succesfully, stops further execution
	StopOnFailureOf []int64 `protobuf:"varint,6,rep,packed,name=stop_on_failure_of,json=stopOnFailureOf,proto3" json:"stop_on_failure_of,omitempty"`
	//optional array of dependent AutoTxs that should be executed succesfully in their latest call before upcomming execution is allowed
	SkipOnFailureOf []int64 `protobuf:"varint,7,rep,packed,name=skip_on_failure_of,json=skipOnFailureOf,proto3" json:"skip_on_failure_of,omitempty"`
	//optional array of dependent autotxs that should fail their latest call before upcomming execution is allowed
	SkipOnSuccessOf []int64 `protobuf:"varint,8,rep,packed,name=skip_on_success_of,json=skipOnSuccessOf,proto3" json:"skip_on_success_of,omitempty"`
}

func (m *ExecutionConditions) Reset()         { *m = ExecutionConditions{} }
func (m *ExecutionConditions) String() string { return proto.CompactTextString(m) }
func (*ExecutionConditions) ProtoMessage()    {}
func (*ExecutionConditions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f87850278d17cf9d, []int{3}
}
func (m *ExecutionConditions) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionConditions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionConditions.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecutionConditions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionConditions.Merge(m, src)
}
func (m *ExecutionConditions) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionConditions) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionConditions.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionConditions proto.InternalMessageInfo

// AutoTxHistory execution history
type AutoTxHistory struct {
	History []AutoTxHistoryEntry `protobuf:"bytes,1,rep,name=history,proto3" json:"history"`
}

func (m *AutoTxHistory) Reset()         { *m = AutoTxHistory{} }
func (m *AutoTxHistory) String() string { return proto.CompactTextString(m) }
func (*AutoTxHistory) ProtoMessage()    {}
func (*AutoTxHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_f87850278d17cf9d, []int{4}
}
func (m *AutoTxHistory) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AutoTxHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AutoTxHistory.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AutoTxHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoTxHistory.Merge(m, src)
}
func (m *AutoTxHistory) XXX_Size() int {
	return m.Size()
}
func (m *AutoTxHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoTxHistory.DiscardUnknown(m)
}

var xxx_messageInfo_AutoTxHistory proto.InternalMessageInfo

// AutoTxHistoryEntry provides a the history of AutoTx interchain tx call
type AutoTxHistoryEntry struct {
	ScheduledExecTime time.Time   `protobuf:"bytes,1,opt,name=scheduled_exec_time,json=scheduledExecTime,proto3,stdtime" json:"scheduled_exec_time"`
	ActualExecTime    time.Time   `protobuf:"bytes,2,opt,name=actual_exec_time,json=actualExecTime,proto3,stdtime" json:"actual_exec_time"`
	ExecFee           types2.Coin `protobuf:"bytes,3,opt,name=exec_fee,json=execFee,proto3" json:"exec_fee"`
	// whether all messages are executed, independent of succesfull result
	Executed bool `protobuf:"varint,4,opt,name=executed,proto3" json:"executed,omitempty"`
	//timed out from execution over IBC
	TimedOut bool `protobuf:"varint,5,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	// errors from execution, if executed and no error the execution was succesfull
	Errors []string `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	//will be empty when save_msg_responses is false
	MsgResponses []*types.Any `protobuf:"bytes,7,rep,name=msg_responses,json=msgResponses,proto3" json:"msg_responses,omitempty"`
}

func (m *AutoTxHistoryEntry) Reset()         { *m = AutoTxHistoryEntry{} }
func (m *AutoTxHistoryEntry) String() string { return proto.CompactTextString(m) }
func (*AutoTxHistoryEntry) ProtoMessage()    {}
func (*AutoTxHistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f87850278d17cf9d, []int{5}
}
func (m *AutoTxHistoryEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AutoTxHistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AutoTxHistoryEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AutoTxHistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoTxHistoryEntry.Merge(m, src)
}
func (m *AutoTxHistoryEntry) XXX_Size() int {
	return m.Size()
}
func (m *AutoTxHistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoTxHistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AutoTxHistoryEntry proto.InternalMessageInfo

// Params defines the params for activeness of AutoTxs on governance proposals.
type Params struct {
	AutoTxFundsCommission      int64 `protobuf:"varint,1,opt,name=AutoTxFundsCommission,proto3" json:"AutoTxFundsCommission,omitempty"`
	AutoTxFlexFeeMul           int64 `protobuf:"varint,2,opt,name=AutoTxFlexFeeMul,proto3" json:"AutoTxFlexFeeMul,omitempty"`
	AutoTxConstantFee          int64 `protobuf:"varint,3,opt,name=AutoTxConstantFee,proto3" json:"AutoTxConstantFee,omitempty"`
	RecurringAutoTxConstantFee int64 `protobuf:"varint,4,opt,name=RecurringAutoTxConstantFee,proto3" json:"RecurringAutoTxConstantFee,omitempty"`
	//  Maximum period for self-executing AutoTx
	MaxAutoTxDuration time.Duration `protobuf:"bytes,5,opt,name=MaxAutoTxDuration,proto3,stdduration" json:"max_auto_tx_duration,omitempty"`
	//  Minimum period for self-executing AutoTx
	MinAutoTxDuration time.Duration `protobuf:"bytes,6,opt,name=MinAutoTxDuration,proto3,stdduration" json:"min_auto_tx_duration,omitempty"`
	//  Minimum period for self-executing AutoTx
	MinAutoTxInterval time.Duration `protobuf:"bytes,8,opt,name=MinAutoTxInterval,proto3,stdduration" json:"min_auto_tx_interval,omitempty"`
	//relayer rewards in uinto for each message type 0=SDK,1=Wasm, 2=Osmo. Rewards are in uinto and topped up in the module account by alloc module.
	RelayerRewards []int64 `protobuf:"varint,9,rep,packed,name=relayer_rewards,json=relayerRewards,proto3" json:"relayer_rewards,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_f87850278d17cf9d, []int{6}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AutoTxInfo)(nil), "trst.autoibctx.v1beta1.AutoTxInfo")
	proto.RegisterType((*ICAConfig)(nil), "trst.autoibctx.v1beta1.ICAConfig")
	proto.RegisterType((*ExecutionConfiguration)(nil), "trst.autoibctx.v1beta1.ExecutionConfiguration")
	proto.RegisterType((*ExecutionConditions)(nil), "trst.autoibctx.v1beta1.ExecutionConditions")
	proto.RegisterType((*AutoTxHistory)(nil), "trst.autoibctx.v1beta1.AutoTxHistory")
	proto.RegisterType((*AutoTxHistoryEntry)(nil), "trst.autoibctx.v1beta1.AutoTxHistoryEntry")
	proto.RegisterType((*Params)(nil), "trst.autoibctx.v1beta1.Params")
}

func init() {
	proto.RegisterFile("trst/autoibctx/v1beta1/types.proto", fileDescriptor_f87850278d17cf9d)
}

var fileDescriptor_f87850278d17cf9d = []byte{
	// 1232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4f, 0x73, 0x1b, 0x35,
	0x14, 0xcf, 0xd6, 0x8e, 0xff, 0x28, 0x49, 0xeb, 0xa8, 0x21, 0xe3, 0x04, 0x6a, 0x07, 0x33, 0x03,
	0x99, 0x92, 0xda, 0xd3, 0x42, 0x0f, 0xed, 0x01, 0xc6, 0xeb, 0x34, 0x53, 0xc3, 0xb4, 0xe9, 0x2c,
	0xe6, 0x02, 0x33, 0x68, 0xe4, 0x5d, 0xd9, 0xd1, 0x64, 0x77, 0xe5, 0x91, 0xb4, 0xed, 0xfa, 0xca,
	0x27, 0xe8, 0xb1, 0x47, 0x8e, 0xcc, 0x70, 0xe5, 0x1b, 0x70, 0x29, 0x9c, 0x7a, 0xe4, 0x64, 0xc0,
	0x9d, 0xe1, 0xc0, 0xa7, 0x60, 0x24, 0xed, 0x6e, 0xfc, 0x27, 0x29, 0x0d, 0x37, 0xe9, 0xbd, 0xdf,
	0xef, 0x27, 0xe9, 0xe9, 0xbd, 0x27, 0x81, 0x86, 0xe4, 0x42, 0xb6, 0x70, 0x24, 0x19, 0xed, 0xbb,
	0x32, 0x6e, 0x3d, 0xbd, 0xdd, 0x27, 0x12, 0xdf, 0x6e, 0xc9, 0xf1, 0x88, 0x88, 0xe6, 0x88, 0x33,
	0xc9, 0xe0, 0xb6, 0xc2, 0x34, 0x33, 0x4c, 0x33, 0xc1, 0xec, 0x6e, 0x0d, 0xd9, 0x90, 0x69, 0x48,
	0x4b, 0x8d, 0x0c, 0x7a, 0xb7, 0x3e, 0x64, 0x6c, 0xe8, 0x93, 0x96, 0x9e, 0xf5, 0xa3, 0x41, 0x4b,
	0xd2, 0x80, 0x08, 0x89, 0x83, 0x51, 0x02, 0xa8, 0x2d, 0x02, 0xbc, 0x88, 0x63, 0x49, 0x59, 0x98,
	0xf8, 0x77, 0x16, 0xfd, 0x38, 0x1c, 0xa7, 0x2e, 0x97, 0x89, 0x80, 0x09, 0x64, 0x16, 0x35, 0x93,
	0x54, 0xd5, 0xcc, 0x5a, 0x7d, 0x2c, 0x48, 0x76, 0x0a, 0x97, 0xd1, 0x44, 0xb5, 0xf1, 0xcb, 0x2a,
	0x00, 0xed, 0x48, 0xb2, 0x5e, 0xdc, 0x0d, 0x07, 0x0c, 0xde, 0x00, 0xab, 0x32, 0x46, 0xd4, 0xab,
	0x5a, 0x7b, 0xd6, 0x7e, 0xde, 0x2e, 0x4d, 0x27, 0xf5, 0x7c, 0x2f, 0xee, 0x1e, 0x3a, 0x79, 0x19,
	0x77, 0x3d, 0xb8, 0x05, 0x56, 0xd9, 0xb3, 0x90, 0xf0, 0xea, 0x95, 0x3d, 0x6b, 0xbf, 0xec, 0x98,
	0x89, 0xb2, 0xfa, 0xb8, 0x4f, 0xfc, 0x6a, 0xce, 0x58, 0xf5, 0x04, 0xd6, 0xc1, 0xda, 0x80, 0x10,
	0x84, 0x3d, 0x8f, 0x13, 0x21, 0xaa, 0x79, 0xed, 0x03, 0x03, 0x42, 0xda, 0xc6, 0x02, 0xef, 0x82,
	0x7c, 0x20, 0x86, 0xa2, 0xba, 0xba, 0x97, 0xdb, 0x5f, 0xbb, 0xb3, 0xd5, 0x34, 0xe7, 0x6b, 0xa6,
	0xe7, 0x6b, 0xb6, 0xc3, 0xb1, 0xbd, 0xf6, 0xdb, 0xcf, 0xb7, 0x8a, 0xc2, 0x3b, 0x6d, 0x3e, 0x12,
	0x43, 0x47, 0xc3, 0xe1, 0xd7, 0xa0, 0x44, 0x43, 0x49, 0xf8, 0x53, 0xec, 0x57, 0x0b, 0x7b, 0xd6,
	0xfe, 0xda, 0x9d, 0x9d, 0x25, 0xea, 0x61, 0x12, 0x3a, 0xbb, 0xf6, 0x72, 0x52, 0x5f, 0xf9, 0x67,
	0x52, 0x87, 0x29, 0xe5, 0x80, 0x05, 0x54, 0x92, 0x60, 0x24, 0xc7, 0x2f, 0xfe, 0xa8, 0x5b, 0x4e,
	0x26, 0x05, 0x3b, 0x00, 0x08, 0x89, 0xb9, 0x44, 0xea, 0x5e, 0xaa, 0x45, 0x2d, 0xbc, 0xbb, 0x24,
	0xdc, 0x4b, 0x2f, 0xcd, 0x2e, 0x29, 0xe5, 0xe7, 0x4a, 0xa3, 0xac, 0x79, 0xca, 0x03, 0xdb, 0xa0,
	0x4c, 0x62, 0xe2, 0x1a, 0x8d, 0xd2, 0x25, 0x34, 0x4a, 0x8a, 0xa6, 0x25, 0x3e, 0x07, 0x25, 0x12,
	0x7a, 0x46, 0xa1, 0x7c, 0x09, 0x85, 0x22, 0x09, 0x3d, 0x2d, 0xf0, 0x25, 0xb8, 0x1a, 0x8d, 0x3c,
	0x2c, 0x09, 0x3a, 0xa1, 0x42, 0x32, 0x3e, 0xae, 0x02, 0x1d, 0xe0, 0xb7, 0x93, 0xd9, 0x30, 0xdc,
	0x87, 0x86, 0x0a, 0x8f, 0x01, 0xa0, 0x2e, 0x46, 0x2e, 0x0b, 0x07, 0x74, 0x58, 0x5d, 0xd3, 0xfb,
	0x79, 0xbf, 0x79, 0x7e, 0xe2, 0x37, 0xbb, 0x9d, 0x76, 0x47, 0x03, 0xed, 0x8d, 0xe9, 0xa4, 0x5e,
	0xce, 0xa6, 0x4e, 0x99, 0xba, 0xd8, 0x0c, 0x61, 0x0f, 0x6c, 0x18, 0xb1, 0xe4, 0x86, 0xaa, 0xeb,
	0x5a, 0xb3, 0x79, 0x91, 0xe6, 0x83, 0x98, 0xb8, 0x91, 0x02, 0x76, 0x66, 0x59, 0xce, 0xbc, 0x48,
	0xe3, 0x27, 0x0b, 0x9c, 0x2d, 0x07, 0x3f, 0x00, 0xc5, 0x11, 0xe3, 0x32, 0x4d, 0xe3, 0xb2, 0x0d,
	0xa6, 0x93, 0x7a, 0xe1, 0x09, 0xe3, 0xb2, 0x7b, 0xe8, 0x14, 0x94, 0xab, 0xeb, 0xc1, 0xbb, 0x7a,
	0x23, 0x21, 0x71, 0x95, 0x80, 0x82, 0xea, 0x94, 0xb6, 0x2b, 0xd3, 0x49, 0x7d, 0xbd, 0x93, 0x39,
	0xba, 0x87, 0xce, 0xfa, 0x19, 0xac, 0xeb, 0x41, 0x1b, 0xc0, 0x13, 0x26, 0x24, 0x9a, 0xe7, 0xea,
	0xc4, 0xb7, 0xb7, 0xa6, 0x93, 0x7a, 0xe5, 0x21, 0x13, 0x72, 0x8e, 0x5f, 0x39, 0x99, 0xb7, 0x78,
	0x8d, 0xc9, 0x15, 0xb0, 0x7d, 0xfe, 0xb9, 0xe0, 0x01, 0x80, 0x02, 0x3f, 0x25, 0x28, 0x10, 0x43,
	0xc4, 0x89, 0x18, 0xb1, 0x50, 0x10, 0xa1, 0x4f, 0x51, 0x72, 0x2a, 0xca, 0xa3, 0xea, 0x20, 0xb5,
	0xc3, 0x8f, 0xc1, 0xa6, 0xbe, 0x2e, 0x1a, 0x0e, 0x91, 0x47, 0x05, 0xee, 0xfb, 0xc4, 0x9c, 0xa3,
	0xe4, 0x54, 0x52, 0xc7, 0x61, 0x62, 0x87, 0x1f, 0x82, 0x6b, 0x42, 0xb2, 0x11, 0x62, 0x21, 0x12,
	0x91, 0xeb, 0xaa, 0x9a, 0xcc, 0x69, 0xe8, 0x86, 0x32, 0x1f, 0x87, 0x5f, 0x19, 0xe3, 0x2c, 0x6e,
	0x80, 0xa9, 0x1f, 0x71, 0xa2, 0x6b, 0x37, 0xc3, 0x1d, 0x19, 0x23, 0xbc, 0x07, 0x76, 0x06, 0xd8,
	0xf7, 0xfb, 0xd8, 0x3d, 0x45, 0x92, 0x21, 0xdd, 0x0a, 0x50, 0x1f, 0xfb, 0x38, 0x74, 0x49, 0x75,
	0x55, 0x33, 0xb6, 0x53, 0x40, 0x8f, 0x1d, 0x2b, 0xb7, 0x6d, 0xbc, 0xf0, 0x3b, 0xf0, 0x1e, 0x27,
	0x9c, 0x0c, 0xa9, 0x90, 0x84, 0x23, 0x95, 0x60, 0x78, 0xa0, 0x46, 0x2a, 0xe9, 0x59, 0x24, 0x75,
	0x59, 0x97, 0xec, 0x1b, 0xd3, 0x49, 0x7d, 0xc7, 0xc9, 0x70, 0xdd, 0x4e, 0xbb, 0xad, 0x50, 0x3d,
	0x03, 0x72, 0x76, 0xce, 0x24, 0xba, 0x2e, 0x9e, 0x75, 0x35, 0x7e, 0xb5, 0xc0, 0xf5, 0xd9, 0x00,
	0x7b, 0x54, 0x0d, 0x54, 0xbc, 0xe0, 0x42, 0x08, 0x10, 0x1b, 0xe8, 0xfe, 0x93, 0x73, 0xae, 0xcd,
	0x45, 0xe1, 0x78, 0x30, 0x0b, 0x4e, 0xe2, 0xa0, 0xc0, 0x85, 0x59, 0x70, 0x12, 0x8a, 0x04, 0x7c,
	0x4a, 0x17, 0xc1, 0xc5, 0x04, 0x7c, 0x4a, 0x2f, 0x02, 0xcf, 0x6c, 0xa3, 0x34, 0x0b, 0xce, 0xb6,
	0xd1, 0xf8, 0x16, 0x6c, 0x98, 0xfe, 0x9c, 0x96, 0xe4, 0x17, 0xa0, 0x98, 0x16, 0xb6, 0xa5, 0x0b,
	0xfb, 0xe6, 0x45, 0xb5, 0x33, 0xc7, 0x7b, 0x10, 0x4a, 0x3e, 0xb6, 0xf3, 0xaa, 0xd0, 0x9d, 0x54,
	0xa0, 0xf1, 0x7d, 0x0e, 0xc0, 0x65, 0x14, 0xec, 0x81, 0xeb, 0xc2, 0x3d, 0x21, 0x5e, 0xe4, 0x13,
	0x0f, 0x9d, 0x35, 0x34, 0xeb, 0x12, 0xed, 0x68, 0x33, 0x13, 0x78, 0x90, 0x76, 0xb6, 0xc7, 0xa0,
	0x82, 0x5d, 0x19, 0x61, 0x7f, 0x46, 0xf2, 0xca, 0x25, 0x24, 0xaf, 0x1a, 0x76, 0xa6, 0x77, 0x1f,
	0xe8, 0xae, 0x89, 0x06, 0x84, 0xe8, 0x4c, 0x56, 0x0f, 0x41, 0xf2, 0xf6, 0xa9, 0xd7, 0x2e, 0x0b,
	0x43, 0x87, 0xd1, 0x30, 0x3d, 0xb8, 0x22, 0x1c, 0x11, 0x02, 0x77, 0x0d, 0x37, 0x92, 0xc4, 0x4b,
	0xb2, 0x3b, 0x9b, 0xc3, 0x77, 0x41, 0x59, 0xed, 0xcd, 0x43, 0x2a, 0x15, 0x4d, 0x22, 0x97, 0xb4,
	0xe1, 0x38, 0x92, 0x70, 0x1b, 0x14, 0x08, 0xe7, 0x8c, 0x0b, 0x9d, 0x09, 0x65, 0x27, 0x99, 0xc1,
	0x7b, 0x60, 0x63, 0xbe, 0x66, 0x8b, 0x17, 0xbf, 0x6a, 0xce, 0x7a, 0x30, 0x53, 0xc5, 0x8d, 0xbf,
	0xf3, 0xa0, 0xf0, 0x04, 0x73, 0x1c, 0x08, 0xf8, 0x29, 0x78, 0xc7, 0x5c, 0xc7, 0x51, 0x14, 0x7a,
	0xa2, 0xc3, 0x82, 0x80, 0x0a, 0xa1, 0xba, 0xa4, 0x0a, 0x7d, 0xce, 0x39, 0xdf, 0x09, 0x6f, 0x82,
	0x4a, 0xe2, 0xf0, 0x49, 0x7c, 0x44, 0xc8, 0xa3, 0xc8, 0xd7, 0x81, 0xcd, 0x39, 0x4b, 0x76, 0x78,
	0x00, 0x36, 0x8d, 0xad, 0xc3, 0x42, 0x21, 0x71, 0x28, 0x8f, 0x92, 0xe8, 0xe5, 0x9c, 0x65, 0x07,
	0xfc, 0x0c, 0xec, 0x3a, 0xc4, 0x8d, 0x38, 0xa7, 0xe1, 0x70, 0x99, 0x96, 0xd7, 0xb4, 0x37, 0x20,
	0xa0, 0x00, 0x9b, 0x8f, 0x70, 0x6c, 0xec, 0xe9, 0x9b, 0xac, 0x43, 0xfa, 0xc6, 0x47, 0xfb, 0x66,
	0xf2, 0x68, 0xd7, 0x02, 0x1c, 0x23, 0x95, 0xd6, 0x48, 0xc6, 0x28, 0xfd, 0x0d, 0x2d, 0x3c, 0xe0,
	0xcb, 0xfa, 0x7a, 0x51, 0x1a, 0x2e, 0x2c, 0x5a, 0x78, 0xfb, 0x45, 0x69, 0xf8, 0xdf, 0x8b, 0x2e,
	0xea, 0xcf, 0x2d, 0xda, 0x4d, 0xbf, 0x27, 0xa5, 0xff, 0xb5, 0xe8, 0x05, 0x5f, 0x95, 0x65, 0x7d,
	0xf8, 0x11, 0xb8, 0xc6, 0x89, 0x8f, 0xc7, 0x84, 0x23, 0x4e, 0x9e, 0x61, 0xee, 0x89, 0x6a, 0x59,
	0x77, 0x91, 0xab, 0x89, 0xd9, 0x31, 0xd6, 0xfb, 0xf9, 0x17, 0x3f, 0xd4, 0x57, 0xec, 0xc7, 0x2f,
	0xff, 0xaa, 0xad, 0xfc, 0x38, 0xad, 0x59, 0x2f, 0xa7, 0x35, 0xeb, 0xd5, 0xb4, 0x66, 0xfd, 0x39,
	0xad, 0x59, 0xcf, 0x5f, 0xd7, 0x56, 0x5e, 0xbd, 0xae, 0xad, 0xfc, 0xfe, 0xba, 0xb6, 0xf2, 0xcd,
	0xc1, 0x90, 0xca, 0x93, 0xa8, 0xdf, 0x74, 0x59, 0xd0, 0x52, 0x4d, 0xc5, 0xc7, 0x7d, 0xa1, 0x07,
	0xad, 0x58, 0x7f, 0x86, 0x6f, 0xd1, 0xbe, 0x7b, 0x4b, 0xc6, 0xe6, 0x1b, 0xdc, 0x2f, 0xe8, 0x03,
	0x7d, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x66, 0xa6, 0xc0, 0x2d, 0x0b, 0x00, 0x00,
}

func (this *AutoTxInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AutoTxInfo)
	if !ok {
		that2, ok := that.(AutoTxInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TxID != that1.TxID {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if this.FeeAddress != that1.FeeAddress {
		return false
	}
	if len(this.Msgs) != len(that1.Msgs) {
		return false
	}
	for i := range this.Msgs {
		if !this.Msgs[i].Equal(that1.Msgs[i]) {
			return false
		}
	}
	if this.Interval != that1.Interval {
		return false
	}
	if !this.StartTime.Equal(that1.StartTime) {
		return false
	}
	if !this.ExecTime.Equal(that1.ExecTime) {
		return false
	}
	if !this.EndTime.Equal(that1.EndTime) {
		return false
	}
	if len(this.UpdateHistory) != len(that1.UpdateHistory) {
		return false
	}
	for i := range this.UpdateHistory {
		if !this.UpdateHistory[i].Equal(that1.UpdateHistory[i]) {
			return false
		}
	}
	if !this.ICAConfig.Equal(that1.ICAConfig) {
		return false
	}
	if !this.Configuration.Equal(that1.Configuration) {
		return false
	}
	return true
}
func (this *ICAConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ICAConfig)
	if !ok {
		that2, ok := that.(ICAConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.PortID != that1.PortID {
		return false
	}
	if this.ConnectionID != that1.ConnectionID {
		return false
	}
	if this.HostConnectionID != that1.HostConnectionID {
		return false
	}
	return true
}
func (this *ExecutionConfiguration) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExecutionConfiguration)
	if !ok {
		that2, ok := that.(ExecutionConfiguration)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SaveMsgResponses != that1.SaveMsgResponses {
		return false
	}
	if this.UpdatingDisabled != that1.UpdatingDisabled {
		return false
	}
	if this.StopOnSuccess != that1.StopOnSuccess {
		return false
	}
	if this.StopOnFailure != that1.StopOnFailure {
		return false
	}
	if this.FallbackToOwnerBalance != that1.FallbackToOwnerBalance {
		return false
	}
	if this.ReregisterICAAfterTimeout != that1.ReregisterICAAfterTimeout {
		return false
	}
	return true
}
func (this *ExecutionConditions) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExecutionConditions)
	if !ok {
		that2, ok := that.(ExecutionConditions)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.StopOnSuccessOf) != len(that1.StopOnSuccessOf) {
		return false
	}
	for i := range this.StopOnSuccessOf {
		if this.StopOnSuccessOf[i] != that1.StopOnSuccessOf[i] {
			return false
		}
	}
	if len(this.StopOnFailureOf) != len(that1.StopOnFailureOf) {
		return false
	}
	for i := range this.StopOnFailureOf {
		if this.StopOnFailureOf[i] != that1.StopOnFailureOf[i] {
			return false
		}
	}
	if len(this.SkipOnFailureOf) != len(that1.SkipOnFailureOf) {
		return false
	}
	for i := range this.SkipOnFailureOf {
		if this.SkipOnFailureOf[i] != that1.SkipOnFailureOf[i] {
			return false
		}
	}
	if len(this.SkipOnSuccessOf) != len(that1.SkipOnSuccessOf) {
		return false
	}
	for i := range this.SkipOnSuccessOf {
		if this.SkipOnSuccessOf[i] != that1.SkipOnSuccessOf[i] {
			return false
		}
	}
	return true
}
func (this *AutoTxHistory) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AutoTxHistory)
	if !ok {
		that2, ok := that.(AutoTxHistory)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.History) != len(that1.History) {
		return false
	}
	for i := range this.History {
		if !this.History[i].Equal(&that1.History[i]) {
			return false
		}
	}
	return true
}
func (this *AutoTxHistoryEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AutoTxHistoryEntry)
	if !ok {
		that2, ok := that.(AutoTxHistoryEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ScheduledExecTime.Equal(that1.ScheduledExecTime) {
		return false
	}
	if !this.ActualExecTime.Equal(that1.ActualExecTime) {
		return false
	}
	if !this.ExecFee.Equal(&that1.ExecFee) {
		return false
	}
	if this.Executed != that1.Executed {
		return false
	}
	if this.TimedOut != that1.TimedOut {
		return false
	}
	if len(this.Errors) != len(that1.Errors) {
		return false
	}
	for i := range this.Errors {
		if this.Errors[i] != that1.Errors[i] {
			return false
		}
	}
	if len(this.MsgResponses) != len(that1.MsgResponses) {
		return false
	}
	for i := range this.MsgResponses {
		if !this.MsgResponses[i].Equal(that1.MsgResponses[i]) {
			return false
		}
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.AutoTxFundsCommission != that1.AutoTxFundsCommission {
		return false
	}
	if this.AutoTxFlexFeeMul != that1.AutoTxFlexFeeMul {
		return false
	}
	if this.AutoTxConstantFee != that1.AutoTxConstantFee {
		return false
	}
	if this.RecurringAutoTxConstantFee != that1.RecurringAutoTxConstantFee {
		return false
	}
	if this.MaxAutoTxDuration != that1.MaxAutoTxDuration {
		return false
	}
	if this.MinAutoTxDuration != that1.MinAutoTxDuration {
		return false
	}
	if this.MinAutoTxInterval != that1.MinAutoTxInterval {
		return false
	}
	if len(this.RelayerRewards) != len(that1.RelayerRewards) {
		return false
	}
	for i := range this.RelayerRewards {
		if this.RelayerRewards[i] != that1.RelayerRewards[i] {
			return false
		}
	}
	return true
}
func (m *AutoTxInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AutoTxInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AutoTxInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Configuration != nil {
		{
			size, err := m.Configuration.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.ICAConfig != nil {
		{
			size, err := m.ICAConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if len(m.UpdateHistory) > 0 {
		for iNdEx := len(m.UpdateHistory) - 1; iNdEx >= 0; iNdEx-- {
			n, err := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdateHistory[iNdEx], dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdateHistory[iNdEx]):])
			if err != nil {
				return 0, err
			}
			i -= n
			i = encodeVarintTypes(dAtA, i, uint64(n))
			i--
			dAtA[i] = 0x52
		}
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintTypes(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x4a
	n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExecTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExecTime):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintTypes(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x42
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintTypes(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x3a
	n6, err6 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.Interval, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Interval):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintTypes(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0x32
	if len(m.Msgs) > 0 {
		for iNdEx := len(m.Msgs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Msgs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.FeeAddress) > 0 {
		i -= len(m.FeeAddress)
		copy(dAtA[i:], m.FeeAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.FeeAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if m.TxID != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TxID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ICAConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ICAConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ICAConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HostConnectionID) > 0 {
		i -= len(m.HostConnectionID)
		copy(dAtA[i:], m.HostConnectionID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.HostConnectionID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ConnectionID) > 0 {
		i -= len(m.ConnectionID)
		copy(dAtA[i:], m.ConnectionID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ConnectionID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PortID) > 0 {
		i -= len(m.PortID)
		copy(dAtA[i:], m.PortID)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PortID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ExecutionConfiguration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionConfiguration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionConfiguration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReregisterICAAfterTimeout {
		i--
		if m.ReregisterICAAfterTimeout {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.FallbackToOwnerBalance {
		i--
		if m.FallbackToOwnerBalance {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.StopOnFailure {
		i--
		if m.StopOnFailure {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.StopOnSuccess {
		i--
		if m.StopOnSuccess {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.UpdatingDisabled {
		i--
		if m.UpdatingDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.SaveMsgResponses {
		i--
		if m.SaveMsgResponses {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ExecutionConditions) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionConditions) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionConditions) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SkipOnSuccessOf) > 0 {
		dAtA8 := make([]byte, len(m.SkipOnSuccessOf)*10)
		var j7 int
		for _, num1 := range m.SkipOnSuccessOf {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintTypes(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SkipOnFailureOf) > 0 {
		dAtA10 := make([]byte, len(m.SkipOnFailureOf)*10)
		var j9 int
		for _, num1 := range m.SkipOnFailureOf {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA10[j9] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j9++
			}
			dAtA10[j9] = uint8(num)
			j9++
		}
		i -= j9
		copy(dAtA[i:], dAtA10[:j9])
		i = encodeVarintTypes(dAtA, i, uint64(j9))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.StopOnFailureOf) > 0 {
		dAtA12 := make([]byte, len(m.StopOnFailureOf)*10)
		var j11 int
		for _, num1 := range m.StopOnFailureOf {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA12[j11] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j11++
			}
			dAtA12[j11] = uint8(num)
			j11++
		}
		i -= j11
		copy(dAtA[i:], dAtA12[:j11])
		i = encodeVarintTypes(dAtA, i, uint64(j11))
		i--
		dAtA[i] = 0x32
	}
	if len(m.StopOnSuccessOf) > 0 {
		dAtA14 := make([]byte, len(m.StopOnSuccessOf)*10)
		var j13 int
		for _, num1 := range m.StopOnSuccessOf {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA14[j13] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j13++
			}
			dAtA14[j13] = uint8(num)
			j13++
		}
		i -= j13
		copy(dAtA[i:], dAtA14[:j13])
		i = encodeVarintTypes(dAtA, i, uint64(j13))
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}

func (m *AutoTxHistory) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AutoTxHistory) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AutoTxHistory) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.History) > 0 {
		for iNdEx := len(m.History) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.History[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AutoTxHistoryEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AutoTxHistoryEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AutoTxHistoryEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MsgResponses) > 0 {
		for iNdEx := len(m.MsgResponses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MsgResponses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Errors) > 0 {
		for iNdEx := len(m.Errors) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Errors[iNdEx])
			copy(dAtA[i:], m.Errors[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Errors[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.TimedOut {
		i--
		if m.TimedOut {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Executed {
		i--
		if m.Executed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.ExecFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n16, err16 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ActualExecTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ActualExecTime):])
	if err16 != nil {
		return 0, err16
	}
	i -= n16
	i = encodeVarintTypes(dAtA, i, uint64(n16))
	i--
	dAtA[i] = 0x12
	n17, err17 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ScheduledExecTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ScheduledExecTime):])
	if err17 != nil {
		return 0, err17
	}
	i -= n17
	i = encodeVarintTypes(dAtA, i, uint64(n17))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RelayerRewards) > 0 {
		dAtA19 := make([]byte, len(m.RelayerRewards)*10)
		var j18 int
		for _, num1 := range m.RelayerRewards {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA19[j18] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j18++
			}
			dAtA19[j18] = uint8(num)
			j18++
		}
		i -= j18
		copy(dAtA[i:], dAtA19[:j18])
		i = encodeVarintTypes(dAtA, i, uint64(j18))
		i--
		dAtA[i] = 0x4a
	}
	n20, err20 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MinAutoTxInterval, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinAutoTxInterval):])
	if err20 != nil {
		return 0, err20
	}
	i -= n20
	i = encodeVarintTypes(dAtA, i, uint64(n20))
	i--
	dAtA[i] = 0x42
	n21, err21 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MinAutoTxDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinAutoTxDuration):])
	if err21 != nil {
		return 0, err21
	}
	i -= n21
	i = encodeVarintTypes(dAtA, i, uint64(n21))
	i--
	dAtA[i] = 0x32
	n22, err22 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxAutoTxDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxAutoTxDuration):])
	if err22 != nil {
		return 0, err22
	}
	i -= n22
	i = encodeVarintTypes(dAtA, i, uint64(n22))
	i--
	dAtA[i] = 0x2a
	if m.RecurringAutoTxConstantFee != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RecurringAutoTxConstantFee))
		i--
		dAtA[i] = 0x20
	}
	if m.AutoTxConstantFee != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AutoTxConstantFee))
		i--
		dAtA[i] = 0x18
	}
	if m.AutoTxFlexFeeMul != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AutoTxFlexFeeMul))
		i--
		dAtA[i] = 0x10
	}
	if m.AutoTxFundsCommission != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AutoTxFundsCommission))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AutoTxInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TxID != 0 {
		n += 1 + sovTypes(uint64(m.TxID))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.FeeAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Msgs) > 0 {
		for _, e := range m.Msgs {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.Interval)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExecTime)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovTypes(uint64(l))
	if len(m.UpdateHistory) > 0 {
		for _, e := range m.UpdateHistory {
			l = github_com_cosmos_gogoproto_types.SizeOfStdTime(e)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.ICAConfig != nil {
		l = m.ICAConfig.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Configuration != nil {
		l = m.Configuration.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ICAConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PortID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ConnectionID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.HostConnectionID)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ExecutionConfiguration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SaveMsgResponses {
		n += 2
	}
	if m.UpdatingDisabled {
		n += 2
	}
	if m.StopOnSuccess {
		n += 2
	}
	if m.StopOnFailure {
		n += 2
	}
	if m.FallbackToOwnerBalance {
		n += 2
	}
	if m.ReregisterICAAfterTimeout {
		n += 2
	}
	return n
}

func (m *ExecutionConditions) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StopOnSuccessOf) > 0 {
		l = 0
		for _, e := range m.StopOnSuccessOf {
			l += sovTypes(uint64(e))
		}
		n += 1 + sovTypes(uint64(l)) + l
	}
	if len(m.StopOnFailureOf) > 0 {
		l = 0
		for _, e := range m.StopOnFailureOf {
			l += sovTypes(uint64(e))
		}
		n += 1 + sovTypes(uint64(l)) + l
	}
	if len(m.SkipOnFailureOf) > 0 {
		l = 0
		for _, e := range m.SkipOnFailureOf {
			l += sovTypes(uint64(e))
		}
		n += 1 + sovTypes(uint64(l)) + l
	}
	if len(m.SkipOnSuccessOf) > 0 {
		l = 0
		for _, e := range m.SkipOnSuccessOf {
			l += sovTypes(uint64(e))
		}
		n += 1 + sovTypes(uint64(l)) + l
	}
	return n
}

func (m *AutoTxHistory) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.History) > 0 {
		for _, e := range m.History {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *AutoTxHistoryEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ScheduledExecTime)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ActualExecTime)
	n += 1 + l + sovTypes(uint64(l))
	l = m.ExecFee.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.Executed {
		n += 2
	}
	if m.TimedOut {
		n += 2
	}
	if len(m.Errors) > 0 {
		for _, s := range m.Errors {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.MsgResponses) > 0 {
		for _, e := range m.MsgResponses {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AutoTxFundsCommission != 0 {
		n += 1 + sovTypes(uint64(m.AutoTxFundsCommission))
	}
	if m.AutoTxFlexFeeMul != 0 {
		n += 1 + sovTypes(uint64(m.AutoTxFlexFeeMul))
	}
	if m.AutoTxConstantFee != 0 {
		n += 1 + sovTypes(uint64(m.AutoTxConstantFee))
	}
	if m.RecurringAutoTxConstantFee != 0 {
		n += 1 + sovTypes(uint64(m.RecurringAutoTxConstantFee))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxAutoTxDuration)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinAutoTxDuration)
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MinAutoTxInterval)
	n += 1 + l + sovTypes(uint64(l))
	if len(m.RelayerRewards) > 0 {
		l = 0
		for _, e := range m.RelayerRewards {
			l += sovTypes(uint64(e))
		}
		n += 1 + sovTypes(uint64(l)) + l
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AutoTxInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AutoTxInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AutoTxInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxID", wireType)
			}
			m.TxID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msgs = append(m.Msgs, &types.Any{})
			if err := m.Msgs[len(m.Msgs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.Interval, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExecTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateHistory = append(m.UpdateHistory, time.Time{})
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&(m.UpdateHistory[len(m.UpdateHistory)-1]), dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ICAConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ICAConfig == nil {
				m.ICAConfig = &ICAConfig{}
			}
			if err := m.ICAConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Configuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Configuration == nil {
				m.Configuration = &ExecutionConfiguration{}
			}
			if err := m.Configuration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ICAConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ICAConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ICAConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostConnectionID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostConnectionID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionConfiguration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionConfiguration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionConfiguration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SaveMsgResponses", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SaveMsgResponses = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatingDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UpdatingDisabled = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StopOnSuccess", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StopOnSuccess = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StopOnFailure", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StopOnFailure = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FallbackToOwnerBalance", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FallbackToOwnerBalance = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReregisterICAAfterTimeout", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReregisterICAAfterTimeout = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionConditions) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionConditions: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionConditions: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 5:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.StopOnSuccessOf = append(m.StopOnSuccessOf, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTypes
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTypes
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.StopOnSuccessOf) == 0 {
					m.StopOnSuccessOf = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.StopOnSuccessOf = append(m.StopOnSuccessOf, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field StopOnSuccessOf", wireType)
			}
		case 6:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.StopOnFailureOf = append(m.StopOnFailureOf, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTypes
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTypes
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.StopOnFailureOf) == 0 {
					m.StopOnFailureOf = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.StopOnFailureOf = append(m.StopOnFailureOf, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field StopOnFailureOf", wireType)
			}
		case 7:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.SkipOnFailureOf = append(m.SkipOnFailureOf, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTypes
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTypes
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.SkipOnFailureOf) == 0 {
					m.SkipOnFailureOf = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.SkipOnFailureOf = append(m.SkipOnFailureOf, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipOnFailureOf", wireType)
			}
		case 8:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.SkipOnSuccessOf = append(m.SkipOnSuccessOf, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTypes
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTypes
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.SkipOnSuccessOf) == 0 {
					m.SkipOnSuccessOf = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.SkipOnSuccessOf = append(m.SkipOnSuccessOf, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field SkipOnSuccessOf", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AutoTxHistory) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AutoTxHistory: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AutoTxHistory: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field History", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.History = append(m.History, AutoTxHistoryEntry{})
			if err := m.History[len(m.History)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AutoTxHistoryEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AutoTxHistoryEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AutoTxHistoryEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledExecTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ScheduledExecTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualExecTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ActualExecTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExecFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Executed = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimedOut", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimedOut = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Errors", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Errors = append(m.Errors, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgResponses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgResponses = append(m.MsgResponses, &types.Any{})
			if err := m.MsgResponses[len(m.MsgResponses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoTxFundsCommission", wireType)
			}
			m.AutoTxFundsCommission = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AutoTxFundsCommission |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoTxFlexFeeMul", wireType)
			}
			m.AutoTxFlexFeeMul = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AutoTxFlexFeeMul |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutoTxConstantFee", wireType)
			}
			m.AutoTxConstantFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AutoTxConstantFee |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecurringAutoTxConstantFee", wireType)
			}
			m.RecurringAutoTxConstantFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecurringAutoTxConstantFee |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAutoTxDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxAutoTxDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAutoTxDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MinAutoTxDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinAutoTxInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MinAutoTxInterval, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RelayerRewards = append(m.RelayerRewards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTypes
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTypes
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTypes
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.RelayerRewards) == 0 {
					m.RelayerRewards = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTypes
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RelayerRewards = append(m.RelayerRewards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerRewards", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
