global:
  api-listen-addr: :5183
  timeout: 20s
  memo: ""
  light-cache-size: 20
chains:
  into:
    type: cosmos
    value:
      key: rly1
      chain-id: intento-dev-1
      rpc-addr: http://into1:26657
      account-prefix: into
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02uinto
      coin-type: 118
      debug: false
      timeout: 40s
      output-format: json
      sign-mode: direct
  gaia:
    type: cosmos
    value:
      key: rly2
      chain-id: GAIA
      rpc-addr: http://gaia1:26657
      account-prefix: cosmos
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02uatom
      coin-type: 118
      debug: false
      timeout: 40s
      output-format: json
      sign-mode: direct
  osmo:
    type: cosmos
    value:
      key: rly4
      chain-id: OSMO
      rpc-addr: http://osmo1:26657
      account-prefix: osmo
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02uosmo
      coin-type: 118
      debug: true
      timeout: 40s
      output-format: json
      sign-mode: direct
  host:
    type: cosmos
    value:
      key: rly6
      chain-id: HOST
      rpc-addr: http://host1:26657
      account-prefix: into
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02ucosm
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  # {new-host-zone}:
  #   type: cosmos
  #   value:
  #     key: rly{N}
  #     chain-id: {CHAIN_ID}
  #     rpc-addr: http://{node_prefix}1:26657
  #     account-prefix: {bech32_hrp_account_prefix}
  #     keyring-backend: test
  #     gas-adjustment: 1.3
  #     gas-prices: 0.02{minimal_denom}
  #     coin-type: {coin-type}
  #     debug: false
  #     timeout: 20s
  #     output-format: json
  #     sign-mode: direct

paths:
  into-gaia:
    src:
      chain-id: intento-dev-1
      client-id: 07-tendermint-0
      connection-id: connection-1
    dst:
      chain-id: GAIA
      client-id: 07-tendermint-0
      connection-id: connection-1
    src-channel-filter:
      rule: ""
      channel-list: []
  into-osmo:
    src:
      chain-id: intento-dev-1
      client-id: 07-tendermint-0
      connection-id: connection-3
    dst:
      chain-id: OSMO #osmo-test-5
      client-id: 07-tendermint-0
      connection-id: connection-1
    src-channel-filter:
      rule: ""
      channel-list: []
  into-host:
    src:
      chain-id: intento-dev-1
    dst:
      chain-id: HOST
    src-channel-filter:
      rule: ""
      channel-list: []
  # into-{new-host-zone}:
  #   src:
  #     chain-id: intento-dev-1
  #   dst:
  #     chain-id: {CHAIN_ID}
  #   src-channel-filter:
  #     rule: ""
  #     channel-list: []
