name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: "Specify the INTO version tag"

permissions:
  contents: write
  packages: write

jobs:
  compile-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [linux]
    name: intento ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set GO Environment Variables
        run: |
          echo "GOOS=${{ matrix.targetos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "GOOS is set to: ${{ matrix.targetos }}"
          echo "GOARCH is set to: ${{ matrix.arch }}"

      - name: Compile intento
        run: make build

      - uses: actions/upload-artifact@v4
        with:
          name: intentod_${{ matrix.targetos }}_${{ matrix.arch }}
          path: build/intentod

  fetch-artifact-and-release:
      runs-on: ubuntu-latest
      needs: compile-and-release
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Get Version
          id: get_version
          run: |
            version=${{ github.event.inputs.version || github.ref }}
            version=${version#refs/tags/}  # Removes 'refs/tags/' prefix
            version=${version%_}  # Removes trailing underscore (if any)
            echo "version=$version" >> $GITHUB_ENV
            echo "Version: $version"

        - name: Download Intento Build Artifact (Linux AMD64)
          uses: actions/download-artifact@v4
          with:
            name: intentod_linux_amd64
            path: build/

        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: build/intentod
            asset_name: intentod_linux_amd64_${{ env.version }}
            asset_content_type: application/octet-stream
        - name: Authenticate with GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          
        - name: Build and Push Docker Image
          env:
            DOCKER_BUILDKIT: 1
          shell: bash
          run: |
            tag=ghcr.io/trstlabs/intento:${{ env.version }}
            docker build -t $tag .
            docker push $tag